using Commerce.API.Contract.V1.Common.Responses;
using Commerce.API.Contract.V1.Customers.Responses;

namespace Commerce.API.Contract.V1.Products.Responses;

public record ProductResponse(string Id,
    string Brand,
    string Model,
    string? OwnerId,
    CustomerBriefResponse? Owner,
    string? DealerId,
    CustomerBriefResponse? Dealer,
    string? DeviceType,
    string? PanelModel,
    string? PanelSerialNumber,
    string? WarrantyCardNumber,
    DateTimeOffset? DateOfPurchase,
    string? InvoiceNumber,
    decimal? PurchasePrice,
    IList<OrderId> OrderIds,
    bool? IsUnrepairable,
    DateTimeOffset? DateOfDemandForCompensation,
    string? DemanderFullName,
    string? Lot,
    DateTimeOffset? ProductionDate,
    int? SerialId,
    DateTimeOffset CreatedAt,
    Guid CreatedBy,
    DateTimeOffset? LastModifiedAt,
    Guid? LastModifiedBy,
    int Version,
    bool IsActive,
    bool IsDeleted) : AuditableResponse(CreatedAt, 
    CreatedBy, 
    LastModifiedAt, 
    LastModifiedBy,
    Version,
    IsActive, 
    IsDeleted);